### ISSUE TITLE
Cursor appears on next line after typing (sometimes)

### ISSUE THREAD

**Issue by manstie** [reedsy/quill-cursors#60] opened 2020-11-12 09:23 UTC
How to reproduce:

1. Go to https://codepen.io/manstie/pen/wvWRgRW
2. type something in one line, press enter, type something in second line
3. go back to first line and type one more letter and the cursor for the other user will probably be on the second line

![image](https://user-images.githubusercontent.com/12475567/98920709-254c4700-251c-11eb-8a30-f2dcbb73988d.png)

**Comment by alecgibson** [comment] 2020-11-12 09:29
I think this is a duplicate of https://github.com/reedsy/quill-cursors/issues/56

**Comment by manstie** [comment] 2020-11-12 09:32
Would disabling cursor events when typing fix this?

**Comment by manstie** [comment] 2020-11-12 09:34
removing `transformOnTextChange: true` seems to correct this. Whoops!

**Comment by alecgibson** [comment] 2020-11-12 09:37
Basically, it's complex. I think as I outline in the above issue, the future of this library is probably going to be becoming a bit more "dumb", and leaning on the underlying data-syncing libraries to handle the difficult case of keeping cursors in sync.

**Closed** 2020-11-12 09:36 UTC
